---
- hosts: tag_Name_{{ lookup('env','AWS_PREFIX') }}_vpn
  serial: 1
  gather_facts: yes
  gather_subset: '!all'
  pre_tasks:
    - uri:
        url: http://ipecho.net/plain
        return_content: yes
      register: ip_facts
  roles:
    - {role: angstwad.docker_ubuntu, become: true, tags: docker}
  post_tasks:
    - name: pull kylemanna/openvpn
      become: true
      docker_image:
        name: kylemanna/openvpn
    - name: start VPN container
      become: true
      docker_container:
        image: kylemanna/openvpn
        name: openvpn
        env:
          OVPN_DATA: openvpn_data
        volumes:
          - openvpn_data:/etc/openvpn
        command: "ovpn_genconfig -u udp://{{ ip_facts.content }}"

# docker run -v openvpn_data:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://35.157.151.5
# docker run -v openvpn_data:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki pass
# docker run -v openvpn_data:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn

# docker run -v openvpn_data:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full mbp nopass
# docker run -v openvpn_data:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient mbp > mbp.ovpn

scp -i /vagrant/tmp/ssh/170320-key.pem ubuntu@35.157.151.5:/home/ubuntu/mbp.ovpn /vagrant/tmp/mbp.ovpn