---
- hosts: tag_Name_{{ lookup('env','AWS_PREFIX') }}_vpn
  serial: 1
  gather_facts: yes
  gather_subset: '!all'
  roles:
    - {role: angstwad.docker_ubuntu, become: true, tags: docker}
  post_tasks:
    - name: pull kylemanna/openvpn
      become: true
      docker_image:
        name: kylemanna/openvpn