---
- hosts: tag_Name_{{ lookup('env','AWS_PREFIX') }}_vpn
  serial: 1
  gather_facts: yes
  gather_subset: '!all'
  pre_tasks:
    - uri:
        url: http://ipecho.net/plain
        return_content: yes
      register: ip_facts
      tags: always
  roles:
    - {role: angstwad.docker_ubuntu, become: true, tags: docker}
  post_tasks:
    - name: pull kylemanna/openvpn
      become: true
      docker_image:
        name: kylemanna/openvpn
        
    - name: generate container config
      become: true
      docker_container:
        image: kylemanna/openvpn
        name: openvpn
        env:
          OVPN_DATA: openvpn_data
        volumes:
          - openvpn_data:/etc/openvpn
        command: "ovpn_genconfig -u udp://{{ ip_facts.content }}"
    - block:

        - pause:
            prompt: "Pause until ovpn_initpki has been run manually. \nSSH to instance at {{ ip_facts.content }} and run:\ndocker run -v openvpn_data:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki "
        - name: ovpn_initpki
          become: true
          docker_container:
            image: kylemanna/openvpn
            name: openvpn
            env:
              OVPN_DATA: openvpn_data
            volumes:
              - openvpn_data:/etc/openvpn
            command: "ovpn_initpki nopass"
      tags: pki


    - name: run container
      become: true
      docker_container:
        image: kylemanna/openvpn
        name: openvpn
        env:
          OVPN_DATA: openvpn_data
        volumes:
          - openvpn_data:/etc/openvpn
        published_ports: 
          - 1194:1194
        capabilities:
          - NET_ADMIN
      tags: run



# docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn