---
- hosts: tag_Name_{{ lookup('env','AWS_PREFIX') }}_vpn
  serial: 1
  gather_facts: yes
  gather_subset: '!all' 
  vars:
    OVPN_DATA: "ovpn-data"

  pre_tasks:
    - block:
        - set_fact:
            OVPN_DIR: "/home/ubuntu/ovpn-data0"
            OVPN_DATA: "ovpn-data0"
        - file:
            path: "{{ OVPN_DIR }}"
            state: directory
            mode: 0755

      when: ALTERNATIVE is defined
      tags: always

    - block:
      - name: Get VPC public IP
        uri:
          url: http://ipecho.net/plain
          return_content: yes
        register: ip_facts
        tags: always
      - set_fact:
          public_ip: "{{ ip_facts.content }}"
      when: PUBLIC_IP is undefined

    - set_fact:
        public_ip: "{{ PUBLIC_IP }}"
      when: PUBLIC_IP is defined
      tags: always

  roles:
    - {role: angstwad.docker_ubuntu, become: true, tags: docker}

  post_tasks:
    - set_fact:
        env_vars: 
          OVPN_DATA: "{{ OVPN_DATA }}"
        vols:
          - "{{ OVPN_DATA }}:/etc/openvpn"
        docker_ports:
          - 1194:1194/udp
        docker_caps: NET_ADMIN
        server_target: "{{ public_ip }}"
        docker_name: openvpn
        client_name: mbp1
        docker_privileged: no
        extra_config: ''
      tags: always

    - set_fact:
        vols:
          - "{{ OVPN_DIR }}:/etc/openvpn"
        docker_name: openvpn0
        client_name: mbp2
        docker_privileged: yes
        docker_ports:
          - 1195:1194/udp 
        extra_config: "-r 172.16.254.0/24"
      when: ALTERNATIVE is defined
      tags: always

    - name: pull kylemanna/openvpn
      become: true
      tags: pull
      docker_image:
        name: kylemanna/openvpn

    - set_fact:
        server_target: "{{ public_ip }}:1195"
      when: ALTERNATIVE is defined


    - name: Generate openvpn config
      become: true
      tags: generate
      docker_container:
        name: "{{ docker_name }}"
        image: kylemanna/openvpn
        env: "{{ env_vars }}"
        volumes: "{{ vols }}"
        command: "ovpn_genconfig -u udp://{{ server_target }} {{ extra_config }}"


    - pause:
        prompt: "
#   Now log into the VPN instance, e.g.:\n
ssh -v -i {{ lookup('env','VM_TEMP_PATH') }}/ssh/{{ lookup('env','AWS_PREFIX') }}-key.pem ubuntu@{{ public_ip }}\n
\n
#   and generate certificates using ovpn_initpki, e.g.:\n
sudo docker run -v {{ vols[0] }} --rm -it kylemanna/openvpn ovpn_initpki\n
\n
#   Press enter to continue
        "

    - copy:
        src: openvpn.conf
        dest: "{{ OVPN_DIR }}"
        owner: ubuntu
        group: ubuntu
        mode: 0644
      when: ALTERNATIVE is defined



    - block:
      - name: Remove previous openvpn container
        become: true
        docker_container:
          name: "{{ docker_name }}"
          image: kylemanna/openvpn
          state: absent

      - name: Start openvpn
        become: true
        docker_container:
          name: "{{ docker_name }}"
          image: kylemanna/openvpn
          env: "{{ env_vars }}"
          volumes: "{{ vols }}"
          capabilities: "{{ docker_caps }}"
          published_ports: "{{ docker_ports }}"
          privileged: yes
      tags: start


    - pause:
        prompt: "
#   Now log into the VPN instance, e.g.:\n
ssh -v -i {{ lookup('env','VM_TEMP_PATH') }}/ssh/{{ lookup('env','AWS_PREFIX') }}-key.pem ubuntu@{{ public_ip }}\n
\n
#   generate client certificates using ovpn_initpki, e.g.:\n
sudo docker run -v {{ vols[0] }} --rm -it kylemanna/openvpn easyrsa build-client-full {{ client_name }} nopass\n
\n
#   retrieve ovpn file:\n
sudo docker run -v {{ vols[0] }} --rm kylemanna/openvpn ovpn_getclient {{ client_name }} > /home/ubuntu/{{ client_name }}.ovpn

\n
#   Press enter to continue
        "

    - name: Fetch ovpn file
      fetch:
        tags: fetch
        flat: yes
        src: "/home/ubuntu/{{ client_name }}.ovpn"
        dest: "{{ lookup('env','VM_TEMP_PATH') }}/"




