---
- hosts: tag_Name_{{ lookup('env','AWS_PREFIX') }}_vpn
  serial: 1
  gather_facts: yes
  gather_subset: '!all' 
  vars:
    OVPN_DATA: "ovpn-data"

  pre_tasks:
    - name: Get VPC public IP
      uri:
        url: http://ipecho.net/plain
        return_content: yes
      register: ip_facts
      tags: always
  roles:
    - {role: angstwad.docker_ubuntu, become: true, tags: docker}
  post_tasks:
    - name: pull kylemanna/openvpn
      become: true
      docker_image:
        name: kylemanna/openvpn